```{r}
library("igraph")
```

## Initialization

```{r}
n <- 6
# An example directed graph
g <- make_graph(edges = c(2, 1, 3, 1, 6, 4, 4, 5, 5, 6), n = n, directed = TRUE) # Changable coefficients
plot(g, main = "Original graph")
```

## Construction of the condensed graph

```{r}
KosarajuSCC <- function(g){  
  #Comparing d with S.node, get the overlapping ones and remove the NA
  getnotNA <- function(d,S.node){
    k <- length(which(d>0))   
    d.useful <- NULL
    d.useful <- subset(d[1:k],match(d[1:k],S.node)>0)
    return(d.useful)
  }
  #-----------------------------------------------------------##
  g.adjacency <- as.matrix(as_adjacency_matrix(g))
  n <- nrow(g.adjacency)
  List.out <- vector(mode="list")
  List.node <- seq(0,0,length.out=n)
  S.node <- seq(from=1,to=n)
##------------------declaration of variables used-------------##
  
  #g <- graph.adjacency(g.adjacency)
  #Mt <- t(M)
  gt <- t(g.adjacency) %>%
    graph.adjacency
  Source.node <- S.node[round(runif(1)*n)]
  Count <- 0
##------------------generate a stack of nodes in graph---------##
##------------------give the topology rank of each nodes-------##
  while (any(S.node != 0)){
    d <- graph.dfs(g,root=Source.node,neimode="out",unreachable=FALSE)
    d.useful <- getnotNA(d$order,S.node)
    k <- length(d.useful)
    for(i in 1:k){
      List.node[n-(Count + i-1)] <- d.useful[k-i+1]
    }
    Count <- Count+k
    S.node[d.useful] <- 0
    if(all(S.node==0)) break
    Source.node <- S.node[S.node!=0][1]
  }  
##------Reverse the directions of all arcs to obtain the transport graph---##
##-------------------------------------------------------------------------##
  Count <- 0
  while (any(List.node !=0)){
    Source.node <- List.node[which(List.node!=0)[1]]
    d <- graph.dfs(gt,root=Source.node,neimode="out",unreachable=FALSE)
    d.useful <- getnotNA(d$order,List.node)
    if(length(d)==0)
      break
    Count <- Count+1
##----Record this SCC and remove all these nodes from the graph and the stack---##
    List.out[[Count]] <- d.useful
    List.node[match(d.useful,List.node)] <- 0
  }
  List.out
}
```

```{r}
library(igraph)

# Function to construct the condensed graph, including isolated SCCs
CondensedGraph <- function(g, scc_list) {
  # Number of SCCs
  num_sccs <- length(scc_list)

  # Map nodes to their SCC
  node_to_scc <- rep(0, vcount(g))
  for (i in seq_along(scc_list)) {
    node_to_scc[scc_list[[i]]] <- i
  }

  # Create a new edge list
  edge_list <- matrix(ncol = 2, nrow = 0)  # Initialize an empty edge matrix
  for (v in V(g)) {
    for (neighbor in neighbors(g, v, mode = "out")) {
      scc_v <- node_to_scc[v]
      scc_neighbor <- node_to_scc[neighbor]
      if (scc_v != scc_neighbor) {  # Avoid self-loops
        edge_list <- rbind(edge_list, c(scc_v, scc_neighbor))
      }
    }
  }

  # Ensure all SCCs (even isolated ones) are included
  condensed_g <- make_empty_graph(n = num_sccs, directed = TRUE)  # Create empty graph with all SCCs
  V(condensed_g)$name <- as.character(seq_len(num_sccs))  # Correctly assign SCC labels

  # Add edges if any exist
  if (nrow(edge_list) > 0) {
    condensed_g <- add_edges(condensed_g, t(edge_list))
  }

  return(condensed_g)
}

# Example usage
sccs <- KosarajuSCC(g)  # Compute SCCs
condensed_graph <- CondensedGraph(g, sccs)  # Construct the condensed graph

# Plot the condensed graph
plot(condensed_graph, main = "Condensed graph", vertex.label = V(condensed_graph)$name)

```

## Search for maximal classes of the condensed graph

```{r}
search_maximal_class <- function(adj_g,i,j) {
  lbs[i] <<- 1
  maxc[j,i] <<- i
  
  for(w in 1:n) {
    if(adj_g[i,w] == 1 & !(w %in% maxc[j,])) {
      search_maximal_class(adj_g,w,j)
    }
  }
}

get_maximal_class <- function(g) {
  lbs <<- rep(0L,n)
  maxc <<- matrix(0,n,n)
  adj_g <- as_adjacency_matrix(g)
  
  num <- 0
  
  for(i in 1:n) {
    if(all(adj_g[,i] == 0)) {
      search_maximal_class(adj_g,i,i)
      num <- num + 1
    }
  }
  
  for(i in 1:n){
    # Loops
    if(lbs[i] == 0) {
      search_maximal_class(adj_g,i,i)
      num <- num + 1
    }
  }
  
  print(paste("Number of maximal classes: ", num))
}
```

## Get the list of maximal classes of the original graph

```{r}
make_list_maxc <- function(sccs,maxc,n) {
  list_maxc <- list()

  for (i in 1:n) {
    tmp_maxc <- c()
    for (j in 1:n) {
      if (maxc[i,j] != 0) {
        tmp_maxc <- c(tmp_maxc,sccs[[maxc[i,j]]])
      }
    }
    if (!is.null(tmp_maxc)) {
      list_maxc <- append(list_maxc,list(tmp_maxc))
    }
  }
  return(list_maxc)
}
```



```{r}
n <- vcount(condensed_graph)
lbs <- rep(0L,n) # Labels for the nodes, global variable
maxc <- matrix(0,n,n) # Maximal classes, global variable

get_maximal_class(condensed_graph)

list_maxc <- make_list_maxc(sccs,maxc,n)

print(list_maxc)
```
